apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  creationTimestamp: "2023-12-27T17:40:35Z"
  generation: 2
  labels:
    team: architecture
  name: pgcluster-qa3
  namespace: default
  resourceVersion: "2058715"
  uid: 80669e65-62da-4c27-a63f-aa6f0aeb3431
spec:
  allowedSourceRanges: null
  connectionPooler:
    mode: transaction
    numberOfInstances: 1
    schema: zalando
    user: lti-qa3-pooled
  enableMasterPoolerLoadBalancer: true
  enableReplicaConnectionPooler: true
  numberOfInstances: 1
  postgresql:
    version: "13"
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: acid
  users:
    lti-admin: [SUPERUSER]
    lti-qa3: [SUPERUSER]
  volume:
    size: 10Gi