kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "pgcluster-qa3"
  namespace: "default"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "13"
  numberOfInstances: 1
  volume:
    size: "10Gi"
  users:
    lti-admin: [SUPERUSER]
    lti-qa3: [SUPERUSER]
  databases:
    qa3: lti-qa3
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  enableMasterPoolerLoadBalancer: false
  enableReplicaConnectionPooler: false
  #connectionPooler:
  #  mode: transaction
  #  numberOfInstances: 1
  #  schema: zalando
  #  user: lti-qa3-pooled
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi