apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-env-overrides
  namespace: default
data:
  USE_WALG_BACKUP: "true"
  BACKUP_SCHEDULE: "0 3,15 * * *" # Schedule a base backup at 3:00 and 15:00
  BACKUP_NUM_TO_RETAIN: "180" # For 2 backups per day, keep 90 days of base backups
  WALG_AZ_PREFIX: "azure://z-pgcluster-backup/$(SCOPE)/$(PGVERSION)"
  #  For point in time recovery/restore
  USE_WALG_RESTORE: "true"
  CLONE_WALG_AZ_PREFIX: "azure://z-pgcluster-backup/$(CLONE_SCOPE)/$(PGVERSION)"
  CLONE_USE_WALG_BACKUP: "true"
  CLONE_USE_WALG_RESTORE: "true"